# REQUIRED CONFIG
BOT_TOKEN = "7566651613:AAGrJ6dffiyN8Xz_fL2As-WUDDkCDo3vZEw"
OWNER_ID = 6004363830
TELEGRAM_API = 25101360
TELEGRAM_HASH = "136cc2036074e0c1db3c2f3070e3cd7d"

# SEMI-REQUIRED, WE SUGGEST TO FILL IT FROM MONGODB
DATABASE_URL = "mongodb+srv://ZinkMovies:0FmbEsW3aH0Me7no@zinkmovies.wn3rs.mongodb.net/?retryWrites=true&w=majority&appName=ZinkMovies"

# OPTIONAL CONFIG
USER_SESSION_STRING = ""
DOWNLOAD_DIR = "/usr/src/app/downloads/"
CMD_SUFFIX = ""
AUTHORIZED_CHATS = ""
SUDO_USERS = ""
DEFAULT_UPLOAD = "rc"
FILELION_API = ""
STREAMWISH_API = ""
EXTENSION_FILTER = ""
INCOMPLETE_TASK_NOTIFIER = False
YT_DLP_OPTIONS = ""
USE_SERVICE_ACCOUNTS = True
NAME_SUBSTITUTE = ""
FFMPEG_CMDS = {}

# INKYPINKY
DELETE_LINKS = False
FSUB_IDS = ""
TOKEN_TIMEOUT = 0
PAID_CHANNEL_ID = 0
PAID_CHANNEL_LINK = ""
SET_COMMANDS = True
METADATA_KEY = "ZinkMovies"
WATERMARK_KEY = "ZinkMovies.com"
LOG_CHAT_ID = 0
LEECH_FILENAME_CAPTION = ""

# GDrive Tools
GDRIVE_ID = ""
IS_TEAM_DRIVE = True 
STOP_DUPLICATE = True
INDEX_URL = ""

# Rclone
RCLONE_PATH = ""
RCLONE_FLAGS = ""
RCLONE_SERVE_URL = ""
RCLONE_SERVE_PORT = 0
RCLONE_SERVE_USER = ""
RCLONE_SERVE_PASS = ""

# Mega credentials
MEGA_EMAIL = ""
MEGA_PASSWORD = ""

# Update
UPSTREAM_REPO = "https://github.com/AeonOrg/Aeon-MLTB"
UPSTREAM_BRANCH = "main"

# Leech
LEECH_SPLIT_SIZE = 0
AS_DOCUMENT = False
MEDIA_GROUP = False
USER_TRANSMISSION = False
MIXED_LEECH = False
LEECH_FILENAME_PREFIX = ""
LEECH_DUMP_CHAT = ""
THUMBNAIL_LAYOUT = ""

# qBittorrent/Aria2c
TORRENT_TIMEOUT = 0
BASE_URL = ""
BASE_URL_PORT = 80
WEB_PINCODE = False

# Queueing system
QUEUE_ALL = 0
QUEUE_DOWNLOAD = 0
QUEUE_UPLOAD = 0

# RSS
RSS_DELAY = 600
RSS_CHAT = ""
RSS_SIZE_LIMIT = 0
